"""Theme -> QSS. The only generator, used by both the mockup preview and QGIS itself.

The final stylesheet is the base QGIS UI theme's resolved QSS followed by QUI's
rules, so specificity and source order resolve identically in preview and in QGIS.
"""

from __future__ import annotations

import re
from collections.abc import Mapping

from .selector_registry import COMPONENTS, Component
from .theme_model import ACCENT_REF, Background, Gradient, StateStyle, Theme, parse_color

QUI_MARKER = "/* ---- QUI ---- */"

_EM_VALUE_RE = re.compile(r"(?<=[\s:])([0-9.]+)(?=em)")


def resolve_ui_theme(
    style_qss: str, variables_qss: str = "", theme_path: str = "", scale: float = 1.0
) -> str:
    """Resolve a QGIS UI theme's ``style.qss`` exactly like ``QgsApplication.setUITheme``.

    ``@theme_path`` becomes *theme_path*; each ``@name: value`` line of
    ``variables.qss`` is substituted in file order (value taken verbatim after the
    first colon); ``em`` values are multiplied by *scale* (``Qgis.UI_SCALE_FACTOR``).
    """
    data = style_qss.replace("@theme_path", theme_path)
    for line in variables_qss.splitlines():
        if line.startswith("@") and ":" in line:
            name, _, value = line.partition(":")
            data = data.replace(name, value)
    if scale != 1.0:
        data = _EM_VALUE_RE.sub(lambda m: f"{float(m.group(1)) * scale:g}", data)
    return data


def generate_qss(theme: Theme, base_qss: str = "", registry: Mapping[str, Component] = COMPONENTS) -> str:
    """Return the complete stylesheet: *base_qss* followed by the theme's rules."""
    name = theme.name.replace("*/", "* /")
    parts = [base_qss.rstrip()] if base_qss.strip() else []
    parts.append(f'{QUI_MARKER}\n/* Theme "{name}", generated by QUI */')
    parts.extend(generate_rules(theme, registry))
    return "\n\n".join(parts) + "\n"


def generate_rules(theme: Theme, registry: Mapping[str, Component] = COMPONENTS) -> list[str]:
    """One QSS rule per (component, state) that has something set, in registry order.

    Components missing from *registry* and states a component does not support are ignored.
    """
    rules = []
    for component in registry.values():
        style = theme.components.get(component.id)
        if style is None or not component.selectors:
            continue
        for state in component.states:
            state_style = style.states.get(state)
            if state_style is None:
                continue
            decls = declarations(state_style, theme.global_style.accent, theme.global_style.opacity)
            if decls:
                selector = ",\n".join(s + component.pseudo(state) for s in component.selectors)
                body = "\n".join(f"    {d};" for d in decls)
                rules.append(f"{selector} {{\n{body}\n}}")
    return rules


def declarations(style: StateStyle, accent: str, opacity: float = 1.0) -> list[str]:
    """QSS declarations (without ``;``) for one state style."""
    out = []
    if style.background is not None:
        out.append(f"background-color: {qss_brush(style.background, accent, opacity)}")
    if style.color is not None:
        out.append(f"color: {qss_color(style.color, accent)}")
    if style.border_width == 0:
        out.append("border-style: none")
    elif style.border_width is not None:
        out += [f"border-width: {style.border_width}px", "border-style: solid"]
    if style.border_color is not None:
        out.append(f"border-color: {qss_color(style.border_color, accent)}")
    if style.border_radius is not None:
        out.append(f"border-radius: {style.border_radius}px")
    if (p := style.padding) is not None:
        out.append(f"padding: {p.top}px {p.right}px {p.bottom}px {p.left}px")
    return out


def qss_color(value: str, accent: str, alpha_factor: float = 1.0) -> str:
    """``#rrggbb`` when opaque, else ``rgba(r, g, b, a)`` with a in 0..255 (Qt's convention)."""
    r, g, b, a = parse_color(accent if value == ACCENT_REF else value)
    a = round(a * alpha_factor)
    return f"#{r:02x}{g:02x}{b:02x}" if a == 255 else f"rgba({r}, {g}, {b}, {a})"


def qss_brush(background: Background, accent: str, opacity: float = 1.0) -> str:
    """A solid color or a ``qlineargradient(...)``, with alpha scaled by *opacity*."""
    if not isinstance(background, Gradient):
        return qss_color(background, accent, opacity)
    g = background
    stops = ", ".join(f"stop: {s.position:g} {qss_color(s.color, accent, opacity)}" for s in g.stops)
    return f"qlineargradient(x1: {g.x1:g}, y1: {g.y1:g}, x2: {g.x2:g}, y2: {g.y2:g}, {stops})"
